apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: NodePort
  selector:
    app: notification-service
  ports:
    - port: 3006
      targetPort: 3006
      nodePort: 30007